# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('publishdate', models.CharField(max_length=128)),
                ('printing', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
            ],
        ),
    ]
